using Animora.SharedKernel.Validation.Clients;

namespace Animora.Desktop.Modules.Clients.Data;

/// <summary>
/// The write seam behind the owner create/edit handler (DIR-03): Stage A composition binds an
/// in-memory fake, Stage C rebinds an EF Core writer (DT-05, INV-20).
/// </summary>
public interface IOwnerWriteStore
{
    /// <summary>
    /// Inserts or updates the owner row identified by <paramref name="ownerId"/>.
    /// </summary>
    /// <param name="ownerId">
    /// The row's <c>UUIDv7</c> id, generated by the handler for a create (INV-03) so the seam never
    /// has to report back a key it assigned.
    /// </param>
    /// <param name="input">
    /// The already-validated command itself (CONV-18, INV-02) — a second copied input shape would
    /// only invite a rule to drift out of <see cref="OwnerValidator"/>. No status flag travels
    /// beside it: unlike staff activation, nothing about an owner is a status change outside
    /// <see cref="IOwnerInput"/>'s own surface.
    /// </param>
    /// <param name="cancellationToken">Propagated to the underlying storage call, no different from
    /// every other seam method in this module.</param>
    /// <remarks>
    /// One call rather than a handler-side sequence: Owner is a synced entity, so the Stage C
    /// implementation writes the row and its outbox row inside a single SQLite transaction
    /// (DT-04, DESK-ARCH-09), and a seam that exposed the two steps separately could not guarantee
    /// that.
    /// </remarks>
    Task SaveAsync(Guid ownerId, IOwnerInput input, CancellationToken cancellationToken);
}
