using Animora.SharedKernel.Validation.Clients;

namespace Animora.Desktop.Modules.Clients.Data;

/// <summary>
/// The write seam behind the patient create/edit handler (DIR-03): Stage A composition binds an
/// in-memory fake, Stage C rebinds an EF Core writer (DT-05, INV-20).
/// </summary>
public interface IPatientWriteStore
{
    /// <summary>
    /// Inserts or updates the patient row identified by <paramref name="patientId"/>.
    /// </summary>
    /// <param name="patientId">
    /// The row's <c>UUIDv7</c> id, generated by the handler for a create (INV-03) so the seam never
    /// has to report back a key it assigned.
    /// </param>
    /// <param name="input">
    /// The already-validated command itself (CONV-18, INV-02) — a second copied input shape would
    /// only invite a rule to drift out of <see cref="PatientValidator"/>. The owner-existence check
    /// the validator leaves to the handler (DOM-03, SH-05) runs before this is ever called, never
    /// inside this seam.
    /// </param>
    /// <param name="isBirthDateEstimated">
    /// Whether <see cref="IPatientInput.BirthDateUtc"/> was derived from a staff-entered
    /// approximate age rather than a precisely known date. Carried beside <paramref name="input"/>
    /// because it is a provenance flag, not an input-shape rule — the same reason
    /// <see cref="IPatientInput"/> omits it, mirroring <c>IStaffWriteStore.SaveAsync</c>'s
    /// <c>isActive</c> parameter.
    /// </param>
    /// <param name="isSterilized">
    /// Whether the patient has been sterilized; a status flag carried beside
    /// <paramref name="input"/> for the same reason as <paramref name="isBirthDateEstimated"/>.
    /// </param>
    /// <param name="cancellationToken">Propagated to the underlying storage call, no different from
    /// every other seam method in this module.</param>
    /// <remarks>
    /// One call rather than a handler-side sequence: Patient is a synced entity, so the Stage C
    /// implementation writes the row and its outbox row inside a single SQLite transaction
    /// (DT-04, DESK-ARCH-09), and a seam that exposed the two steps separately could not guarantee
    /// that.
    /// </remarks>
    Task SaveAsync(
        Guid patientId,
        IPatientInput input,
        bool isBirthDateEstimated,
        bool isSterilized,
        CancellationToken cancellationToken);
}
