using Animora.SharedKernel.Validation.Identity;

namespace Animora.Desktop.Modules.Identity.Data;

/// <summary>
/// The write seam behind the role create/edit handler (DIR-03): Stage A composition binds an
/// in-memory fake, Stage C rebinds an EF Core writer (DT-05, INV-20).
/// </summary>
public interface IRoleWriteStore
{
    /// <summary>
    /// Inserts or updates the role identified by <paramref name="roleId"/>, replacing its assigned
    /// claim keys with <see cref="IRoleInput.PermissionClaimKeys"/>.
    /// </summary>
    /// <param name="roleId">
    /// The role's <c>UUIDv7</c> id, generated by the handler for a create (INV-03).
    /// </param>
    /// <param name="input">
    /// The already-validated command itself (CONV-18, INV-02); catalog membership of its claim keys
    /// is the handler's check (SEC-09), not this seam's.
    /// </param>
    /// <param name="cancellationToken">Propagated to the underlying storage call, no different from
    /// every other seam method in this module.</param>
    /// <remarks>
    /// Claim keys are replaced wholesale rather than diffed by the caller: the role's claim set is
    /// what the screen edits, and the Stage C implementation writes the role, its claim rows and the
    /// outbox row in one transaction (DT-04, DESK-ARCH-09).
    /// <para>
    /// No delete: SEC-11 protects the system-seeded owner-admin role, and removing a role that staff
    /// members still reference is a reassignment flow this phase's screens do not offer.
    /// </para>
    /// </remarks>
    Task SaveAsync(Guid roleId, IRoleInput input, CancellationToken cancellationToken);
}
